name: "NightAuctor/a-flyleaf on deviantArt, but not on deviantArt"
collections:
    da-posts:
        output: true
    gallery:
        output: true
defaults:
  - scope:
      path: "_da-posts"
    values:
      layout: none